// SPDX-License-Identifier: AGPL-3.0-only
// Thin Node.js HTTP → Fetch bridge for the TanStack Start SSR bundle.
// The CLI spawns this file directly via `node serve.mjs`.
// It is a committed source file — not generated by the build.
//
// Build the SSR bundle first: `pnpm --filter @junction/web build`
// The bundle (dist/server/server.js) exports a WinterCG-compatible
// { fetch(request: Request): Promise<Response> } default export.

import { createServer } from "node:http"
import { dirname, join } from "node:path"
import { Readable } from "node:stream"
import { fileURLToPath } from "node:url"

const __dirname = dirname(fileURLToPath(import.meta.url))

let app
try {
  const mod = await import(join(__dirname, "dist/server/server.js"))
  app = mod.default
} catch (err) {
  process.stderr.write(
    `junction web: failed to load built server bundle.\nRun \`pnpm --filter @junction/web build\` first.\n\n${String(err)}\n`,
  )
  process.exit(1)
}

const HOST = process.env.HOST ?? "127.0.0.1"
const PORT = Number(process.env.PORT ?? "4321")
const MAX_BODY_BYTES = 1_048_576 // 1 MB — reject oversized bodies before buffering OOMs us

/** Loopback-only Host check at the HTTP layer — reject DNS-rebinding early + cheaply. */
function isLocalHost(hostHeader) {
  const h = (hostHeader ?? "").toLowerCase()
  const hostname = h.startsWith("[") ? h.slice(0, h.indexOf("]") + 1) : (h.split(":")[0] ?? "")
  return hostname === "127.0.0.1" || hostname === "localhost" || hostname === "[::1]"
}

const server = createServer(async (req, res) => {
  // Defense-in-depth headers (also defends inc-23+ mutations / any future networked mode).
  res.setHeader("X-Content-Type-Options", "nosniff")
  res.setHeader("X-Frame-Options", "DENY")
  res.setHeader("Content-Security-Policy", "frame-ancestors 'none'")

  // HTTP-layer DNS-rebinding guard — reject non-loopback Host before any app logic.
  if (!isLocalHost(req.headers.host)) {
    res.writeHead(403)
    res.end("Forbidden: access restricted to localhost")
    return
  }

  try {
    const url = `http://${req.headers.host ?? `${HOST}:${PORT}`}${req.url}`

    const chunks = []
    let total = 0
    for await (const chunk of req) {
      total += chunk.length
      if (total > MAX_BODY_BYTES) {
        res.writeHead(413)
        res.end("Payload Too Large")
        req.destroy()
        return
      }
      chunks.push(chunk)
    }
    const body =
      req.method !== "GET" && req.method !== "HEAD" && chunks.length > 0
        ? Buffer.concat(chunks)
        : undefined

    // Build Fetch-compatible headers, skipping undefined values
    const headers = new Headers()
    for (const [k, v] of Object.entries(req.headers)) {
      if (v == null) continue
      headers.set(k, Array.isArray(v) ? v.join(", ") : v)
    }

    const fetchReq = new Request(url, {
      method: req.method,
      headers,
      body,
      // @ts-expect-error — duplex is required for streaming request bodies in Node 18+
      duplex: "half",
    })

    const fetchRes = await app.fetch(fetchReq)

    res.statusCode = fetchRes.status
    res.statusMessage = fetchRes.statusText
    for (const [k, v] of fetchRes.headers.entries()) {
      res.setHeader(k, v)
    }
    // Re-assert our security headers in case the app set conflicting values.
    res.setHeader("X-Content-Type-Options", "nosniff")
    res.setHeader("X-Frame-Options", "DENY")

    if (fetchRes.body) {
      // Node 18+ supports ReadableStream → Readable.fromWeb. Handle mid-stream errors:
      // they fire AFTER the try block, so attach an explicit error handler.
      const nodeStream = Readable.fromWeb(fetchRes.body)
      nodeStream.on("error", (err) => {
        process.stderr.write(`junction web: response stream error: ${String(err)}\n`)
        res.destroy()
      })
      nodeStream.pipe(res)
    } else {
      res.end()
    }
  } catch (err) {
    process.stderr.write(`junction web: request error: ${String(err)}\n`)
    if (!res.headersSent) {
      res.writeHead(500)
    }
    res.end("Internal Server Error")
  }
})

server.listen(PORT, HOST, () => {
  process.stdout.write(`junction web dashboard on http://${HOST}:${PORT}\n`)
})

server.on("error", (err) => {
  process.stderr.write(`junction web: server error: ${String(err)}\n`)
  process.exit(1)
})
