// SPDX-License-Identifier: AGPL-3.0-only
// Thin Node.js HTTP → Fetch bridge for the TanStack Start SSR bundle.
// The CLI spawns this file directly via `node serve.mjs`.
// It is a committed source file — not generated by the build.
//
// Build the SSR bundle first: `pnpm --filter @junction/web build`
// The bundle (dist/server/server.js) exports a WinterCG-compatible
// { fetch(request: Request): Promise<Response> } default export.

import { createReadStream } from "node:fs"
import { stat } from "node:fs/promises"
import { createServer } from "node:http"
import { dirname, join, normalize, sep } from "node:path"
import { Readable } from "node:stream"
import { fileURLToPath } from "node:url"

const __dirname = dirname(fileURLToPath(import.meta.url))

// Built client assets (CSS, JS chunks, fonts) live here. The SSR bundle does NOT
// serve them — this file must, or the page loads unstyled. (First needed in inc 23,
// the first increment to emit a real client bundle.)
const CLIENT_DIR = join(__dirname, "dist", "client")

// Minimal extension → Content-Type map for the asset kinds the build emits.
const CONTENT_TYPES = {
  ".css": "text/css; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".woff2": "font/woff2",
  ".woff": "font/woff",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".ico": "image/x-icon",
  ".map": "application/json; charset=utf-8",
}

/**
 * Resolve a request path to a real file INSIDE CLIENT_DIR, or null if it escapes
 * the dir / isn't a file. Path-traversal guard: the normalized absolute path must
 * stay under CLIENT_DIR. Returns { filePath, contentType } on a hit.
 */
async function resolveStaticFile(reqPath) {
  // Strip query/hash; decode percent-encoding (a 404 on malformed input is fine).
  let pathname
  try {
    pathname = decodeURIComponent(reqPath.split("?")[0].split("#")[0])
  } catch {
    return null
  }
  if (!pathname || pathname === "/") return null

  const candidate = normalize(join(CLIENT_DIR, pathname))
  // Must stay within CLIENT_DIR (block ../ traversal). Append sep to avoid a
  // sibling-prefix bypass (e.g. dist/client-evil).
  if (candidate !== CLIENT_DIR && !candidate.startsWith(CLIENT_DIR + sep)) return null

  try {
    const s = await stat(candidate)
    if (!s.isFile()) return null
    const ext = candidate.slice(candidate.lastIndexOf("."))
    return { filePath: candidate, contentType: CONTENT_TYPES[ext] ?? "application/octet-stream" }
  } catch {
    return null
  }
}

let app
try {
  const mod = await import(join(__dirname, "dist/server/server.js"))
  app = mod.default
} catch (err) {
  process.stderr.write(
    `junction web: failed to load built server bundle.\nRun \`pnpm --filter @junction/web build\` first.\n\n${String(err)}\n`,
  )
  process.exit(1)
}

const HOST = process.env.HOST ?? "127.0.0.1"
const PORT = Number(process.env.PORT ?? "4321")
const MAX_BODY_BYTES = 1_048_576 // 1 MB — reject oversized bodies before buffering OOMs us

/** Loopback-only Host check at the HTTP layer — reject DNS-rebinding early + cheaply. */
function isLocalHost(hostHeader) {
  const h = (hostHeader ?? "").toLowerCase()
  const hostname = h.startsWith("[") ? h.slice(0, h.indexOf("]") + 1) : (h.split(":")[0] ?? "")
  return hostname === "127.0.0.1" || hostname === "localhost" || hostname === "[::1]"
}

const server = createServer(async (req, res) => {
  // Defense-in-depth headers (also defends inc-23+ mutations / any future networked mode).
  res.setHeader("X-Content-Type-Options", "nosniff")
  res.setHeader("X-Frame-Options", "DENY")
  res.setHeader("Content-Security-Policy", "frame-ancestors 'none'")

  // HTTP-layer DNS-rebinding guard — reject non-loopback Host before any app logic.
  if (!isLocalHost(req.headers.host)) {
    res.writeHead(403)
    res.end("Forbidden: access restricted to localhost")
    return
  }

  // Serve built client assets directly (CSS/JS/fonts). Only GET/HEAD; everything
  // else (incl. all non-file paths) falls through to the SSR handler below.
  if (req.method === "GET" || req.method === "HEAD") {
    try {
      const hit = await resolveStaticFile(req.url ?? "")
      if (hit) {
        res.statusCode = 200
        res.setHeader("Content-Type", hit.contentType)
        // Hashed asset filenames are content-addressed → safe to cache long.
        res.setHeader("Cache-Control", "public, max-age=31536000, immutable")
        if (req.method === "HEAD") {
          res.end()
          return
        }
        const fileStream = createReadStream(hit.filePath)
        fileStream.on("error", (err) => {
          process.stderr.write(`junction web: static file stream error: ${String(err)}\n`)
          res.destroy()
        })
        fileStream.pipe(res)
        return
      }
    } catch (err) {
      process.stderr.write(`junction web: static serve error: ${String(err)}\n`)
      // fall through to SSR
    }
  }

  try {
    const url = `http://${req.headers.host ?? `${HOST}:${PORT}`}${req.url}`

    const chunks = []
    let total = 0
    for await (const chunk of req) {
      total += chunk.length
      if (total > MAX_BODY_BYTES) {
        res.writeHead(413)
        res.end("Payload Too Large")
        req.destroy()
        return
      }
      chunks.push(chunk)
    }
    const body =
      req.method !== "GET" && req.method !== "HEAD" && chunks.length > 0
        ? Buffer.concat(chunks)
        : undefined

    // Build Fetch-compatible headers, skipping undefined values
    const headers = new Headers()
    for (const [k, v] of Object.entries(req.headers)) {
      if (v == null) continue
      headers.set(k, Array.isArray(v) ? v.join(", ") : v)
    }

    const fetchReq = new Request(url, {
      method: req.method,
      headers,
      body,
      // @ts-expect-error — duplex is required for streaming request bodies in Node 18+
      duplex: "half",
    })

    const fetchRes = await app.fetch(fetchReq)

    res.statusCode = fetchRes.status
    res.statusMessage = fetchRes.statusText
    for (const [k, v] of fetchRes.headers.entries()) {
      res.setHeader(k, v)
    }
    // Re-assert our security headers in case the app set conflicting values.
    res.setHeader("X-Content-Type-Options", "nosniff")
    res.setHeader("X-Frame-Options", "DENY")

    if (fetchRes.body) {
      // Node 18+ supports ReadableStream → Readable.fromWeb. Handle mid-stream errors:
      // they fire AFTER the try block, so attach an explicit error handler.
      const nodeStream = Readable.fromWeb(fetchRes.body)
      nodeStream.on("error", (err) => {
        process.stderr.write(`junction web: response stream error: ${String(err)}\n`)
        res.destroy()
      })
      nodeStream.pipe(res)
    } else {
      res.end()
    }
  } catch (err) {
    process.stderr.write(`junction web: request error: ${String(err)}\n`)
    if (!res.headersSent) {
      res.writeHead(500)
    }
    res.end("Internal Server Error")
  }
})

server.listen(PORT, HOST, () => {
  process.stdout.write(`junction web dashboard on http://${HOST}:${PORT}\n`)
})

server.on("error", (err) => {
  process.stderr.write(`junction web: server error: ${String(err)}\n`)
  process.exit(1)
})
