// SPDX-License-Identifier: AGPL-3.0-only
// AUTO-GENERATED by packages/core/scripts/gen-catalog.mjs — DO NOT EDIT BY HAND.
// Regenerate with `pnpm --filter @junction/core gen:catalog` after adding or
// editing a catalog/<id>/{catalog.json,help.json,tools/*.json} entry.
//
// This is a PINNED, COMMITTED snapshot (increment 30.8 — see
// docs/methods/30.8-app-catalog-schema.md §2a): every entry below was
// validated against AppCatalogEntrySchema at codegen time. index.ts
// re-validates at module load as a belt-and-suspenders check — this file
// carries zero runtime `fs`, so core stays embeddable.

import type { AppCatalogEntry } from "../catalog-schema.js"

export const CATALOG_ENTRIES: readonly AppCatalogEntry[] = [
  {
    id: "github",
    displayName: "GitHub",
    supportedKinds: ["mcp", "cli", "openapi", "graphql"],
    auth: [
      {
        mode: "oauth2",
        providerId: "github",
      },
      {
        mode: "oauth2",
        providerId: "github-app",
      },
      {
        mode: "token",
      },
    ],
    aliases: ["gh"],
    iconSlug: "github",
    surfaces: [
      {
        kind: "openapi",
        displayName: "REST API",
        connection: {
          kind: "openapi",
          specUrl:
            "https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.json",
          baseUrl: "https://api.github.com",
          verifyOperationId: "users/get-authenticated",
        },
        auth: [
          {
            mode: "oauth2",
            providerId: "github",
          },
          {
            mode: "token",
          },
        ],
        build: {
          platformIdTemplate: "{app}-{kind}",
          via: "flattened",
          credential: {
            kind: "oauth2",
            from: "auth",
          },
        },
        verify: {
          kind: "openapi",
          operationId: "users/get-authenticated",
        },
        docs: "https://docs.github.com/en/rest",
        agentGuidance:
          "The full REST surface — repos, issues, PRs, Actions, and more, generated from GitHub's own OpenAPI spec.",
      },
      {
        kind: "graphql",
        displayName: "GraphQL API",
        connection: {
          kind: "graphql",
          endpoint: "https://api.github.com/graphql",
        },
        auth: [
          {
            mode: "oauth2",
            providerId: "github",
          },
          {
            mode: "token",
          },
        ],
        build: {
          platformIdTemplate: "{app}-{kind}",
          via: "flattened",
          credential: {
            kind: "oauth2",
            from: "auth",
          },
        },
        verify: {
          kind: "graphql",
          typenameProbe: true,
        },
        docs: "https://docs.github.com/en/graphql",
        agentGuidance:
          "GitHub's GraphQL v4 API — best for fetching nested/related data (e.g. a repo's issues + labels + assignees) in one call.",
      },
      {
        kind: "mcp",
        displayName: "GitHub MCP Server",
        connection: {
          kind: "mcp",
          transport: "http",
          url: "https://api.githubcopilot.com/mcp/",
        },
        auth: [
          {
            mode: "oauth2",
            providerId: "github",
          },
          {
            mode: "token",
          },
        ],
        build: {
          platformIdTemplate: "{app}-{kind}",
          via: "flattened",
          credential: {
            kind: "oauth2",
            from: "auth",
          },
        },
        verify: {
          kind: "mcp",
          listTools: true,
        },
        docs: "https://github.com/github/github-mcp-server",
        agentGuidance:
          "GitHub's own hosted MCP server — named, curated tools for repos, issues, PRs, and Actions.",
      },
      {
        kind: "cli",
        displayName: "gh CLI",
        connection: {
          kind: "cli",
          credentialEnvVar: "GH_PAT",
        },
        auth: [
          {
            mode: "token",
          },
        ],
        build: {
          platformIdTemplate: "{app}-{kind}",
          via: "descriptor",
          credential: {
            kind: "bearer",
            from: "auth",
          },
        },
        verify: {
          kind: "none",
        },
        docs: "https://cli.github.com/manual",
        agentGuidance:
          "The gh CLI — best for git-adjacent workflows (PR checkout, release upload) the API surfaces don't model as directly.",
        notes: [
          'credentialEnvVar is "GH_PAT" (not gh\'s real "GH_TOKEN") — CliConnectionSchema rejects any *_TOKEN/_SECRET/_KEY suffix. Mapping GH_PAT back to gh\'s actual GH_TOKEN env is a later-increment concern (generic CLI primitives rework).',
        ],
      },
      {
        kind: "http",
        displayName: "Custom REST request",
        connection: {
          kind: "http",
          baseUrl: "https://api.github.com",
        },
        auth: [
          {
            mode: "token",
          },
        ],
        build: {
          platformIdTemplate: "{app}-{kind}",
          via: "descriptor",
          credential: {
            kind: "bearer",
            from: "auth",
          },
        },
        verify: {
          kind: "none",
        },
        starterTools: [
          {
            name: "get_authenticated_user",
            description:
              "Get the currently authenticated GitHub user (GET /user). A minimal, side-effect-free identity check — also GitHub's connect-time verify probe.",
            method: "GET",
            path: "/user",
            params: [],
          },
          {
            name: "get_repo",
            description: "Get a repository by owner and name (GET /repos/{owner}/{repo}).",
            method: "GET",
            path: "/repos/{owner}/{repo}",
            params: [
              {
                name: "owner",
                in: "path",
                type: "string",
                required: true,
              },
              {
                name: "repo",
                in: "path",
                type: "string",
                required: true,
              },
            ],
          },
          {
            name: "list_issues",
            description: "List issues for a repository (GET /repos/{owner}/{repo}/issues).",
            method: "GET",
            path: "/repos/{owner}/{repo}/issues",
            params: [
              {
                name: "owner",
                in: "path",
                type: "string",
                required: true,
              },
              {
                name: "repo",
                in: "path",
                type: "string",
                required: true,
              },
              {
                name: "state",
                in: "query",
                type: "enum",
                required: false,
                description: "Filter by issue state. Default: open.",
                enum: ["open", "closed", "all"],
              },
            ],
          },
        ],
        notes: [
          "GitHub's REST is covered by OpenAPI; add a custom request-tool only for an endpoint the spec doesn't expose.",
          'DELIBERATE PROOF EXCEPTION (increment 30.11, §2d/§4.7): this surface ships tools/http.tools.json starter tools even though GitHub has a spec (making http technically redundant per the app-surface-model gap-filler rule) — it is the smallest real proof of the via:"descriptor" + starterTools connect path end-to-end. A genuinely spec-less app is where http starters truly belong; see docs/futures/revisit-when.md.',
        ],
      },
    ],
    help: {
      category: ["dev-tools", "git-hosting"],
      homepage: "https://github.com",
      statusPage: "https://www.githubstatus.com",
      description: "Git hosting, issues, pull requests, and CI/CD (Actions) for software projects.",
      agentGuidance:
        "Covers repos, issues, PRs, and Actions. Prefer the MCP surface for curated tools; fall back to the CLI for git-adjacent operations MCP doesn't cover.",
      oauthApp: {
        registerUrl: "https://github.com/settings/applications/new",
        callbackPath: "/oauth/callback/github",
      },
      provenance: {
        authoredBy: "junction",
        researchedFrom: [
          "https://docs.github.com/en/rest",
          "https://docs.github.com/en/graphql",
          "https://github.com/github/github-mcp-server",
          "https://cli.github.com/manual",
          "https://integrations.sh",
        ],
        lastReviewed: "2026-07-06",
      },
      install: {
        commands: {
          brew: "brew install gh",
          apt: "apt install gh",
          winget: "winget install --id GitHub.cli",
        },
        verifyCmd: "gh --version",
        minVersion: "2.0.0",
      },
      authSetup: {
        interactive: "gh auth login",
        env: "GH_TOKEN",
        configPath: "~/.config/gh/hosts.yml",
      },
    },
  },
  {
    id: "slack",
    displayName: "Slack",
    supportedKinds: ["openapi", "mcp"],
    auth: [
      {
        mode: "oauth2",
        providerId: "slack",
      },
      {
        mode: "token",
      },
    ],
    iconSlug: "slack",
    surfaces: [
      {
        kind: "openapi",
        displayName: "REST API",
        connection: {
          kind: "openapi",
          specUrl:
            "https://raw.githubusercontent.com/slackapi/slack-api-specs/master/web-api/slack_web_openapi_v2.json",
          baseUrl: "https://slack.com/api/",
          verifyOperationId: "auth_test",
        },
        auth: [
          {
            mode: "oauth2",
            providerId: "slack",
          },
          {
            mode: "token",
          },
        ],
        build: {
          platformIdTemplate: "{app}-{kind}",
          via: "flattened",
          credential: {
            kind: "oauth2",
            from: "auth",
          },
        },
        verify: {
          kind: "openapi",
          operationId: "auth_test",
        },
        docs: "https://docs.slack.dev/apis/web-api/",
        agentGuidance:
          "Prefer REST for full coverage — channels, messages, users, and more, generated from Slack's own OpenAPI spec.",
        notes: [
          "The OpenAPI spec is Swagger 2.0 (not 3.x), and the slackapi/slack-api-specs repo has been archived (read-only since Mar 2024) — stable but no longer tracking newer Web API methods.",
          "Many write methods (e.g. chat.postMessage) are POST form-encoded; the spec's declarations may not match exactly — verification is anchored on auth.test, which needs no scopes and validates any token.",
        ],
      },
      {
        kind: "mcp",
        displayName: "Slack MCP Server (community)",
        connection: {
          kind: "mcp",
          transport: "stdio",
          command: "npx",
          args: ["-y", "slack-mcp-server@1.3.0", "--transport", "stdio"],
          tokenEnvVar: "SLACK_MCP_XOXB_TOKEN",
        },
        auth: [
          {
            mode: "token",
          },
        ],
        build: {
          platformIdTemplate: "{app}-{kind}",
          via: "flattened",
          credential: {
            kind: "bearer",
            from: "auth",
          },
        },
        verify: {
          kind: "mcp",
          listTools: true,
        },
        docs: "https://github.com/korotovsky/slack-mcp-server",
        agentGuidance:
          "Use the community MCP server for curated conversational tools; prefer the REST surface for full API coverage.",
        notes: [
          "Community-maintained (korotovsky/slack-mcp-server), not affiliated with or endorsed by Slack. junction verified bot-token mode at v1.3.0 on 2026-07-11. Version is pinned — review before bumping.",
          "Runs locally over stdio; the bot token is injected into the local process env and never sent to any third party.",
          "Bot/user-token mode only — the XOXC/XOXD browser-session 'stealth' mode is out of scope and security-sensitive.",
        ],
      },
    ],
    help: {
      category: ["communication", "chat"],
      homepage: "https://slack.com/",
      statusPage: "https://slack-status.com/",
      description: "Team messaging — channels, direct messages, and workspace collaboration.",
      agentGuidance:
        "Covers channels, messages, and users. Prefer REST for full coverage; use the community MCP server for curated conversational tools.",
      oauthApp: {
        registerUrl: "https://api.slack.com/apps",
        callbackPath: "/oauth/callback/slack",
      },
      provenance: {
        authoredBy: "junction",
        researchedFrom: [
          "https://docs.slack.dev/apis/web-api/",
          "https://api.slack.com/authentication/oauth-v2",
          "https://api.slack.com/apps",
          "https://github.com/slackapi/slack-api-specs",
          "https://github.com/korotovsky/slack-mcp-server",
          "https://slack-status.com/",
        ],
        lastReviewed: "2026-07-11",
      },
      authSetup: {
        interactive:
          "create an app at https://api.slack.com/apps, add scopes under OAuth & Permissions, install to workspace",
        env: "SLACK_BOT_TOKEN (xoxb-…)",
      },
      notes: [
        "Slack's official `slack` CLI is app-development/deployment tooling only — it cannot do user-data operations (post a message, list channels), so junction ships no CLI surface for Slack. (Also: the `slack` binary name can collide with other host tools.)",
        "Slack operates an official hosted MCP server at https://mcp.slack.com/mcp, but restricts MCP to directory-published or internal apps (unlisted apps prohibited) — unavailable to junction's self-hosted custom-app model as of 2026-07-11.",
      ],
    },
  },
]
