// SPDX-License-Identifier: AGPL-3.0-only
// AUTO-GENERATED by packages/core/scripts/gen-catalog.mjs — DO NOT EDIT BY HAND.
// Regenerate with `pnpm --filter @junction/core gen:catalog` after adding or
// editing a catalog/<id>/{catalog.json,help.json,tools/*.json} entry.
//
// This is a PINNED, COMMITTED snapshot (increment 30.8 — see
// docs/methods/30.8-app-catalog-schema.md §2a): every entry below was
// validated against AppCatalogEntrySchema at codegen time. index.ts
// re-validates at module load as a belt-and-suspenders check — this file
// carries zero runtime `fs`, so core stays embeddable.

import type { AppCatalogEntry } from "../catalog-schema.js"

export const CATALOG_ENTRIES: readonly AppCatalogEntry[] = [
  {
    id: "adyen",
    displayName: "Adyen",
    supportedKinds: ["openapi"],
    auth: [
      {
        mode: "token",
      },
    ],
    iconSlug: "adyen",
  },
  {
    id: "anilist",
    displayName: "AniList",
    supportedKinds: ["graphql"],
    auth: [
      {
        mode: "none",
      },
    ],
    setupHints: ["Public reads need no auth; mutations require OAuth (not modeled here)."],
    iconSlug: "anilist",
  },
  {
    id: "asana",
    displayName: "Asana",
    supportedKinds: ["openapi"],
    auth: [
      {
        mode: "token",
      },
    ],
    iconSlug: "asana",
  },
  {
    id: "atlassian",
    displayName: "Atlassian",
    supportedKinds: ["mcp"],
    auth: [
      {
        mode: "oauth2",
        providerId: "atlassian",
      },
      {
        mode: "token",
      },
    ],
    setupHints: ["Covers Jira and Confluence Cloud sites via the shared Atlassian OAuth app."],
    iconSlug: "atlassian",
  },
  {
    id: "aws",
    displayName: "AWS",
    supportedKinds: ["cli"],
    auth: [
      {
        mode: "token",
      },
    ],
    iconSlug: "aws",
  },
  {
    id: "box",
    displayName: "Box",
    supportedKinds: ["openapi"],
    auth: [
      {
        mode: "token",
      },
    ],
    iconSlug: "box",
  },
  {
    id: "braintree",
    displayName: "Braintree",
    supportedKinds: ["graphql"],
    auth: [
      {
        mode: "token",
      },
    ],
    iconSlug: "braintree",
  },
  {
    id: "brave-search",
    displayName: "Brave Search",
    supportedKinds: ["mcp"],
    auth: [
      {
        mode: "token",
      },
    ],
    iconSlug: "brave",
  },
  {
    id: "cloudflare",
    displayName: "Cloudflare",
    supportedKinds: ["mcp", "cli"],
    auth: [
      {
        mode: "token",
      },
    ],
    iconSlug: "cloudflare",
  },
  {
    id: "contentful",
    displayName: "Contentful",
    supportedKinds: ["graphql"],
    auth: [
      {
        mode: "token",
      },
    ],
    iconSlug: "contentful",
  },
  {
    id: "countries",
    displayName: "Countries (trevorblades)",
    supportedKinds: ["graphql"],
    auth: [
      {
        mode: "none",
      },
    ],
  },
  {
    id: "datocms",
    displayName: "DatoCMS",
    supportedKinds: ["graphql"],
    auth: [
      {
        mode: "token",
      },
    ],
    iconSlug: "datocms",
  },
  {
    id: "digitalocean",
    displayName: "DigitalOcean",
    supportedKinds: ["cli", "openapi"],
    auth: [
      {
        mode: "token",
      },
    ],
    iconSlug: "digitalocean",
  },
  {
    id: "discord",
    displayName: "Discord",
    supportedKinds: ["openapi"],
    auth: [
      {
        mode: "oauth2",
        providerId: "discord",
      },
      {
        mode: "token",
      },
    ],
    iconSlug: "discord",
  },
  {
    id: "doppler",
    displayName: "Doppler",
    supportedKinds: ["cli"],
    auth: [
      {
        mode: "token",
      },
    ],
    setupHints: ["`doppler secrets` prints secret values — treat reads as sensitive."],
  },
  {
    id: "dropbox",
    displayName: "Dropbox",
    supportedKinds: [],
    auth: [
      {
        mode: "oauth2",
        providerId: "dropbox",
      },
    ],
    iconSlug: "dropbox",
  },
  {
    id: "figma",
    displayName: "Figma",
    supportedKinds: ["mcp"],
    auth: [
      {
        mode: "oauth2",
        providerId: "figma",
      },
      {
        mode: "none",
      },
    ],
    setupHints: [
      "The Figma Dev Mode MCP server requires no credential — it trusts the locally-running desktop app.",
      "The REST API (file/comment access) uses OAuth.",
    ],
    iconSlug: "figma",
    help: {
      notes: [
        "The Dev Mode MCP server requires no credential — it trusts the locally-running desktop app. The REST API (file/comment access) uses OAuth.",
      ],
    },
  },
  {
    id: "filesystem",
    displayName: "Filesystem",
    supportedKinds: ["mcp"],
    auth: [
      {
        mode: "none",
      },
    ],
  },
  {
    id: "github",
    displayName: "GitHub",
    supportedKinds: ["mcp", "cli", "openapi", "graphql"],
    auth: [
      {
        mode: "oauth2",
        providerId: "github",
      },
      {
        mode: "oauth2",
        providerId: "github-app",
      },
      {
        mode: "token",
      },
    ],
    aliases: ["gh"],
    iconSlug: "github",
    surfaces: [
      {
        kind: "openapi",
        displayName: "REST API",
        connection: {
          kind: "openapi",
          specUrl:
            "https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.json",
          baseUrl: "https://api.github.com",
          verifyOperationId: "users/get-authenticated",
        },
        auth: [
          {
            mode: "oauth2",
            providerId: "github",
          },
          {
            mode: "token",
          },
        ],
        build: {
          platformIdTemplate: "{app}",
          via: "flattened",
          credential: {
            kind: "oauth2",
            from: "auth",
          },
        },
        verify: {
          kind: "openapi",
          operationId: "users/get-authenticated",
        },
        docs: "https://docs.github.com/en/rest",
        agentGuidance:
          "The full REST surface — repos, issues, PRs, Actions, and more, generated from GitHub's own OpenAPI spec.",
      },
      {
        kind: "graphql",
        displayName: "GraphQL API",
        connection: {
          kind: "graphql",
          endpoint: "https://api.github.com/graphql",
        },
        auth: [
          {
            mode: "oauth2",
            providerId: "github",
          },
          {
            mode: "token",
          },
        ],
        build: {
          platformIdTemplate: "{app}",
          via: "flattened",
          credential: {
            kind: "oauth2",
            from: "auth",
          },
        },
        verify: {
          kind: "graphql",
          typenameProbe: true,
        },
        docs: "https://docs.github.com/en/graphql",
        agentGuidance:
          "GitHub's GraphQL v4 API — best for fetching nested/related data (e.g. a repo's issues + labels + assignees) in one call.",
      },
      {
        kind: "mcp",
        displayName: "GitHub MCP Server",
        connection: {
          kind: "mcp",
          transport: "http",
          url: "https://api.githubcopilot.com/mcp/",
        },
        auth: [
          {
            mode: "oauth2",
            providerId: "github",
          },
          {
            mode: "token",
          },
        ],
        build: {
          platformIdTemplate: "{app}",
          via: "flattened",
          credential: {
            kind: "oauth2",
            from: "auth",
          },
        },
        verify: {
          kind: "mcp",
          listTools: true,
        },
        docs: "https://github.com/github/github-mcp-server",
        agentGuidance:
          "GitHub's own hosted MCP server — named, curated tools for repos, issues, PRs, and Actions.",
      },
      {
        kind: "cli",
        displayName: "gh CLI",
        connection: {
          kind: "cli",
          credentialEnvVar: "GH_PAT",
        },
        auth: [
          {
            mode: "token",
          },
        ],
        build: {
          platformIdTemplate: "{app}",
          via: "descriptor",
          credential: {
            kind: "bearer",
            from: "auth",
          },
        },
        verify: {
          kind: "none",
        },
        docs: "https://cli.github.com/manual",
        agentGuidance:
          "The gh CLI — best for git-adjacent workflows (PR checkout, release upload) the API surfaces don't model as directly.",
        notes: [
          'credentialEnvVar is "GH_PAT" (not gh\'s real "GH_TOKEN") — CliConnectionSchema rejects any *_TOKEN/_SECRET/_KEY suffix. Mapping GH_PAT back to gh\'s actual GH_TOKEN env is a later-increment concern (generic CLI primitives rework).',
        ],
      },
      {
        kind: "http",
        displayName: "Custom REST request",
        connection: {
          kind: "http",
          baseUrl: "https://api.github.com",
        },
        auth: [
          {
            mode: "token",
          },
        ],
        build: {
          platformIdTemplate: "{app}-http",
          via: "descriptor",
          credential: {
            kind: "bearer",
            from: "auth",
          },
        },
        verify: {
          kind: "none",
        },
        notes: [
          "GitHub's REST is covered by OpenAPI; add a custom request-tool only for an endpoint the spec doesn't expose.",
        ],
      },
    ],
    help: {
      category: ["dev-tools", "git-hosting"],
      homepage: "https://github.com",
      statusPage: "https://www.githubstatus.com",
      description: "Git hosting, issues, pull requests, and CI/CD (Actions) for software projects.",
      agentGuidance:
        "Covers repos, issues, PRs, and Actions. Prefer the MCP surface for curated tools; fall back to the CLI for git-adjacent operations MCP doesn't cover.",
      oauthApp: {
        registerUrl: "https://github.com/settings/applications/new",
        callbackPath: "/oauth/callback/github",
      },
      provenance: {
        authoredBy: "junction",
        researchedFrom: [
          "https://docs.github.com/en/rest",
          "https://docs.github.com/en/graphql",
          "https://github.com/github/github-mcp-server",
          "https://cli.github.com/manual",
          "https://integrations.sh",
        ],
        lastReviewed: "2026-07-06",
      },
      install: {
        commands: {
          brew: "brew install gh",
          apt: "apt install gh",
          winget: "winget install --id GitHub.cli",
        },
        verifyCmd: "gh --version",
        minVersion: "2.0.0",
      },
      authSetup: {
        interactive: "gh auth login",
        env: "GH_TOKEN",
        configPath: "~/.config/gh/hosts.yml",
      },
    },
  },
  {
    id: "gitlab",
    displayName: "GitLab",
    supportedKinds: ["cli", "openapi", "graphql"],
    auth: [
      {
        mode: "oauth2",
        providerId: "gitlab",
      },
      {
        mode: "token",
      },
    ],
    aliases: ["glab"],
    iconSlug: "gitlab",
  },
  {
    id: "google",
    displayName: "Google",
    supportedKinds: ["openapi"],
    auth: [
      {
        mode: "oauth2",
        providerId: "google",
      },
    ],
    iconSlug: "google",
  },
  {
    id: "heroku",
    displayName: "Heroku",
    supportedKinds: ["cli"],
    auth: [
      {
        mode: "token",
      },
    ],
    setupHints: ["`heroku config` prints secret values — treat reads as sensitive."],
    iconSlug: "heroku",
  },
  {
    id: "linear",
    displayName: "Linear",
    supportedKinds: ["mcp", "graphql"],
    auth: [
      {
        mode: "oauth2",
        providerId: "linear",
      },
      {
        mode: "token",
      },
    ],
    iconSlug: "linear",
  },
  {
    id: "microsoft",
    displayName: "Microsoft",
    supportedKinds: ["openapi"],
    auth: [
      {
        mode: "oauth2",
        providerId: "microsoft",
      },
    ],
    iconSlug: "microsoft",
  },
  {
    id: "monday",
    displayName: "monday.com",
    supportedKinds: ["graphql"],
    auth: [
      {
        mode: "token",
      },
    ],
  },
  {
    id: "notion",
    displayName: "Notion",
    supportedKinds: ["mcp"],
    auth: [
      {
        mode: "oauth2",
        providerId: "notion",
      },
      {
        mode: "token",
      },
    ],
    iconSlug: "notion",
    help: {
      notes: ["No stable canonical raw OpenAPI spec URL (JS-rendered portal) — MCP + OAuth only."],
    },
  },
  {
    id: "openai",
    displayName: "OpenAI",
    supportedKinds: ["openapi"],
    auth: [
      {
        mode: "token",
      },
    ],
    iconSlug: "openai",
  },
  {
    id: "pagerduty",
    displayName: "PagerDuty",
    supportedKinds: ["openapi"],
    auth: [
      {
        mode: "token",
      },
    ],
    iconSlug: "pagerduty",
  },
  {
    id: "petstore",
    displayName: "Swagger Petstore",
    supportedKinds: ["openapi"],
    auth: [
      {
        mode: "token",
      },
    ],
    setupHints: ["Public demo API — an api_key header is accepted but not required for reads."],
    iconSlug: "swagger",
  },
  {
    id: "playwright",
    displayName: "Playwright",
    supportedKinds: ["mcp"],
    auth: [
      {
        mode: "none",
      },
    ],
    iconSlug: "playwright",
  },
  {
    id: "railway",
    displayName: "Railway",
    supportedKinds: ["cli"],
    auth: [
      {
        mode: "token",
      },
    ],
    setupHints: ["RAILWAY_API_TOKEN is the account-scoped token; RAILWAY_TOKEN is project-scoped."],
    iconSlug: "railway",
  },
  {
    id: "rickandmorty",
    displayName: "Rick and Morty API",
    supportedKinds: ["graphql"],
    auth: [
      {
        mode: "none",
      },
    ],
  },
  {
    id: "saleor",
    displayName: "Saleor",
    supportedKinds: ["graphql"],
    auth: [
      {
        mode: "token",
      },
      {
        mode: "none",
      },
    ],
    setupHints: ["The public demo endpoint needs no auth; authed queries use a Bearer token."],
  },
  {
    id: "sendgrid",
    displayName: "SendGrid",
    supportedKinds: ["openapi"],
    auth: [
      {
        mode: "token",
      },
    ],
    aliases: ["sendgrid-mail"],
  },
  {
    id: "sentry",
    displayName: "Sentry",
    supportedKinds: ["mcp", "cli"],
    auth: [
      {
        mode: "token",
      },
    ],
    iconSlug: "sentry",
  },
  {
    id: "shopify",
    displayName: "Shopify",
    supportedKinds: ["graphql"],
    auth: [
      {
        mode: "token",
      },
    ],
    aliases: ["shopify-admin", "shopify-storefront"],
    iconSlug: "shopify",
  },
  {
    id: "slack",
    displayName: "Slack",
    supportedKinds: ["openapi"],
    auth: [
      {
        mode: "oauth2",
        providerId: "slack",
      },
      {
        mode: "token",
      },
    ],
    iconSlug: "slack",
    help: {
      notes: [
        'MCP variant omitted: the exact npm package (@slack/mcp-server) is not confirmed by fetching the package page — Slack ships here via OAuth + token only. If confirmed later, add "mcp" to supportedKinds.',
      ],
    },
  },
  {
    id: "spotify",
    displayName: "Spotify",
    supportedKinds: [],
    auth: [
      {
        mode: "oauth2",
        providerId: "spotify",
      },
    ],
    iconSlug: "spotify",
  },
  {
    id: "stripe",
    displayName: "Stripe",
    supportedKinds: ["mcp", "cli", "openapi"],
    auth: [
      {
        mode: "token",
      },
    ],
    setupHints: ["Use a Restricted Key for the MCP/CLI path."],
    iconSlug: "stripe",
  },
  {
    id: "supabase",
    displayName: "Supabase",
    supportedKinds: ["mcp", "cli"],
    auth: [
      {
        mode: "token",
      },
    ],
    setupHints: ["Supabase's own OAuth browser flow is not junction's vault — use a PAT instead."],
    iconSlug: "supabase",
  },
  {
    id: "twilio",
    displayName: "Twilio",
    supportedKinds: ["openapi"],
    auth: [
      {
        mode: "token",
      },
    ],
    aliases: ["twilio-accounts"],
    iconSlug: "twilio",
  },
  {
    id: "vercel",
    displayName: "Vercel",
    supportedKinds: ["cli", "openapi"],
    auth: [
      {
        mode: "token",
      },
    ],
    iconSlug: "vercel",
  },
  {
    id: "wpgraphql",
    displayName: "WPGraphQL",
    supportedKinds: ["graphql"],
    auth: [
      {
        mode: "byo",
      },
    ],
    setupHints: ["Self-hosted WordPress site — the endpoint host is user-supplied."],
    iconSlug: "wordpress",
  },
  {
    id: "yelp",
    displayName: "Yelp",
    supportedKinds: ["graphql"],
    auth: [
      {
        mode: "token",
      },
    ],
    iconSlug: "yelp",
  },
  {
    id: "zoom",
    displayName: "Zoom",
    supportedKinds: [],
    auth: [
      {
        mode: "oauth2",
        providerId: "zoom",
      },
    ],
    iconSlug: "zoom",
  },
]
