// SPDX-License-Identifier: AGPL-3.0-only
// Router factory for @junction/web — TanStack Start.
// routeTree.gen.ts is auto-generated by `tsr generate`; gitignored — do not commit it.

import { createRouter } from "@tanstack/react-router"
import { routeTree } from "./routeTree.gen"

export function getRouter() {
  return createRouter({
    routeTree,
    scrollRestoration: true,
  })
}
