// SPDX-License-Identifier: AGPL-3.0-only
// Router factory for @junction/web — TanStack Start.
// routeTree.gen.ts is auto-generated by `tsr generate`; gitignored — do not commit it.

import { createRouter } from "@tanstack/react-router"
import { NotFound } from "./components/not-found"
import { routeTree } from "./routeTree.gen"

export function getRouter() {
  return createRouter({
    routeTree,
    scrollRestoration: true,
    // Render a real 404 for unmatched routes instead of TanStack's generic
    // `<p>Not Found</p>`. Without this, every not-found request (a mistyped
    // path, a browser probe like /favicon.ico) logs a startup warning.
    defaultNotFoundComponent: NotFound,
    // Enable View Transitions for same-document route changes (progressive
    // enhancement — silently no-ops in browsers that don't support the API).
    // The ::view-transition-* CSS in app.css provides the actual animation;
    // prefers-reduced-motion gate is in that CSS.
    defaultViewTransition: true,
    // ── Data freshness ──────────────────────────────────────────────────
    // Preload on hover — near-free on localhost SQLite.
    defaultPreload: "intent",
    // staleTime 0: ALWAYS revalidate the loader on navigation/refresh. Junction's
    // data changes OUT OF BAND (the CLI, other agents, another browser tab), so a
    // 30s "fresh" window meant a refresh could show stale data. Refetching is
    // near-free on localhost SQLite, and hover-preload keeps it flash-free.
    defaultStaleTime: 0,
    // Preloads can be briefly cached (avoids a double-fetch on hover→click).
    defaultPreloadStaleTime: 5_000,
    // Keep loader cache for 30 minutes (GC after that) — for instant back/forward.
    defaultGcTime: 1_800_000,
    // Fast loads (< 1s) don't flash a pending skeleton at all; the outgoing
    // route stays visible. Slow loads show the pending UI only after 1s, and
    // keep it visible for at least 500ms to avoid a janky flash.
    defaultPendingMs: 1000,
    defaultPendingMinMs: 500,
  })
}
