// SPDX-License-Identifier: AGPL-3.0-only
// AUTO-GENERATED by packages/web/scripts/gen-brand-icons.mjs — DO NOT EDIT BY HAND.
// Regenerate with `pnpm --filter @junction/web gen:icons` after changing which
// catalog apps have an iconSlug (packages/core/src/apps/catalog.ts).
//
// This is a PINNED, COMMITTED snapshot (increment 30.5 v2 — see
// docs/methods/30.5-app-lifecycle.md §4): each entry below is real full-color
// brand mark markup extracted from the installed @thesvg/icons devDependency
// at codegen time, parsed into literal JSX (never `dangerouslySetInnerHTML`),
// so it ships fully offline with no runtime dependency on @thesvg/icons.
//
// LICENSE: brand logo data via @thesvg/icons (github.com/glincker/thesvg, MIT
// code), each mark under its upstream license (mostly CC0-1.0) — see
// README.md "Third-party notices". Brand ownership is unaffected.
//
// Category meaning (consumed by brand-icon.tsx):
//   "color"  -> one full-color mark, rendered as-is on both themes (`color`).
//   "themed" -> two pure black/white marks, CSS-swapped by data-theme
//               (`light` visible in light theme, `dark` visible in dark theme).
//   "mono"   -> one currentColor-adapting mark (`mono`).

export type BrandIconCategory = "color" | "themed" | "mono"

export interface BrandIconEntry {
  readonly category: BrandIconCategory
  readonly viewBox: Readonly<Record<string, string>>
  readonly render: Readonly<Record<string, () => React.ReactNode>>
}

export const BRAND_ICONS: Readonly<Record<string, BrandIconEntry>> = {
  github: {
    category: "themed",
    viewBox: {
      light: "0 0 1024 1024",
      dark: "0 0 1024 1024",
    },
    render: {
      light: () => (
        <>
          <path
            fill="#1b1f23"
            fillRule="evenodd"
            d="M512 0C229.12 0 0 229.12 0 512c0 226.56 146.56 417.92 350.08 485.76 25.6 4.48 35.2-10.88 35.2-24.32 0-12.16-.64-52.48-.64-95.36-128.64 23.68-161.92-31.36-172.16-60.16-5.76-14.72-30.72-60.16-52.48-72.32-17.92-9.6-43.52-33.28-.64-33.92 40.32-.64 69.12 37.12 78.72 52.48 46.08 77.44 119.68 55.68 149.12 42.24 4.48-33.28 17.92-55.68 32.64-68.48-113.92-12.8-232.96-56.96-232.96-252.8 0-55.68 19.84-101.76 52.48-137.6-5.12-12.8-23.04-65.28 5.12-135.68 0 0 42.88-13.44 140.8 52.48 40.96-11.52 84.48-17.28 128-17.28s87.04 5.76 128 17.28c97.92-66.56 140.8-52.48 140.8-52.48 28.16 70.4 10.24 122.88 5.12 135.68 32.64 35.84 52.48 81.28 52.48 137.6 0 196.48-119.68 240-233.6 252.8 18.56 16 34.56 46.72 34.56 94.72 0 68.48-.64 123.52-.64 140.8 0 13.44 9.6 29.44 35.2 24.32C877.44 929.92 1024 737.92 1024 512 1024 229.12 794.88 0 512 0"
            clipRule="evenodd"
          />
        </>
      ),
      dark: () => (
        <>
          <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M8 0C3.58 0 0 3.58 0 8C0 11.54 2.29 14.53 5.47 15.59C5.87 15.66 6.02 15.42 6.02 15.21C6.02 15.02 6.01 14.39 6.01 13.72C4 14.09 3.48 13.23 3.32 12.78C3.23 12.55 2.84 11.84 2.5 11.65C2.22 11.5 1.82 11.13 2.49 11.12C3.12 11.11 3.57 11.7 3.72 11.94C4.44 13.15 5.59 12.81 6.05 12.6C6.12 12.08 6.33 11.73 6.56 11.53C4.78 11.33 2.92 10.64 2.92 7.58C2.92 6.71 3.23 5.99 3.74 5.43C3.66 5.23 3.38 4.41 3.82 3.31C3.82 3.31 4.49 3.1 6.02 4.13C6.66 3.95 7.34 3.86 8.02 3.86C8.7 3.86 9.38 3.95 10.02 4.13C11.55 3.09 12.22 3.31 12.22 3.31C12.66 4.41 12.38 5.23 12.3 5.43C12.81 5.99 13.12 6.7 13.12 7.58C13.12 10.65 11.25 11.33 9.47 11.53C9.76 11.78 10.01 12.26 10.01 13.01C10.01 14.08 10 14.94 10 15.21C10 15.42 10.15 15.67 10.55 15.59C13.71 14.53 16 11.53 16 8C16 3.58 12.42 0 8 0Z"
            transform="scale(64)"
            fill="#ffffff"
          />
        </>
      ),
    },
  },
  slack: {
    category: "color",
    viewBox: {
      color: "0 0 2447.6 2452.5",
    },
    render: {
      color: () => (
        <>
          <g clipRule="evenodd" fillRule="evenodd">
            <path
              d="m897.4 0c-135.3.1-244.8 109.9-244.7 245.2-.1 135.3 109.5 245.1 244.8 245.2h244.8v-245.1c.1-135.3-109.5-245.1-244.9-245.3.1 0 .1 0 0 0m0 654h-652.6c-135.3.1-244.9 109.9-244.8 245.2-.2 135.3 109.4 245.1 244.7 245.3h652.7c135.3-.1 244.9-109.9 244.8-245.2.1-135.4-109.5-245.2-244.8-245.3z"
              fill="#36c5f0"
            />
            <path
              d="m2447.6 899.2c.1-135.3-109.5-245.1-244.8-245.2-135.3.1-244.9 109.9-244.8 245.2v245.3h244.8c135.3-.1 244.9-109.9 244.8-245.3zm-652.7 0v-654c.1-135.2-109.4-245-244.7-245.2-135.3.1-244.9 109.9-244.8 245.2v654c-.2 135.3 109.4 245.1 244.7 245.3 135.3-.1 244.9-109.9 244.8-245.3z"
              fill="#2eb67d"
            />
            <path
              d="m1550.1 2452.5c135.3-.1 244.9-109.9 244.8-245.2.1-135.3-109.5-245.1-244.8-245.2h-244.8v245.2c-.1 135.2 109.5 245 244.8 245.2zm0-654.1h652.7c135.3-.1 244.9-109.9 244.8-245.2.2-135.3-109.4-245.1-244.7-245.3h-652.7c-135.3.1-244.9 109.9-244.8 245.2-.1 135.4 109.4 245.2 244.7 245.3z"
              fill="#ecb22e"
            />
            <path
              d="m0 1553.2c-.1 135.3 109.5 245.1 244.8 245.2 135.3-.1 244.9-109.9 244.8-245.2v-245.2h-244.8c-135.3.1-244.9 109.9-244.8 245.2zm652.7 0v654c-.2 135.3 109.4 245.1 244.7 245.3 135.3-.1 244.9-109.9 244.8-245.2v-653.9c.2-135.3-109.4-245.1-244.7-245.3-135.4 0-244.9 109.8-244.8 245.1 0 0 0 .1 0 0"
              fill="#e01e5a"
            />
          </g>
        </>
      ),
    },
  },
}
